name: todo_ai_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  table_calendar: ^3.0.9
  flutter_local_notifications: ^15.1.1
  provider: ^6.1.2
  fluwx: ^3.9.0
  dio: ^5.1.1
  timezone: ^0.9.2
  http: ^1.2.1
  intl: ^0.18.0
  image_picker: ^1.0.4
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

